CadastroAcademico/Models/UserJobManagerView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CadastroAcademico.Models
{
    public class UserJobManagerView
    {
        
        public int JobId { get; set; }

        [StringLength(100, ErrorMessage = "The field {0} can contain maximun {1} and minimun {2} characters", MinimumLength = 5)]
        [Display(Name = "Nombre del Curso")]
        public string CourseName { get; set; }

        [StringLength(100, ErrorMessage = "The field {0} can contain maximun {1} and minimun {2} characters", MinimumLength = 5)]
        [Display(Name = "Nombre de la materia")]
        public string MatterName { get; set; }

        [StringLength(100, ErrorMessage = "The field {0} can contain maximun {1} and minimun {2} characters", MinimumLength = 5)]
        [Display(Name = "Nombre de la tarea")]
        public string JobName { get; set; }

        [StringLength(100, ErrorMessage = "The field {0} can contain maximun {1} and minimun {2} characters", MinimumLength = 5)]
        [Display(Name = "Descripción de la tarea")]
        public string JobDescription { get; set; }

        [Display(Name = "Fecha de inicio")]
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime JobBeginDate { get; set; }

        [Display(Name = "Fecha final")]
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime JobEndDate { get; set; }
       
        public TypeTask TypeTask { get; set; }

        public int? UserJobId { get; set; }

        [Display(Name = "File")]
        public string filePath { get; set; }

        [Display(Name = "File")]
        public HttpPostedFileBase file { get; set; }

        [Display(Name = "Fecha de registro")]
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime RegistrationDate { get; set; }
    }
}

CadastroAcademico/Controllers/UserJobManagersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CadastroAcademico.Models;
using System.IO;

namespace CadastroAcademico.Controllers
{
    [Authorize(Roles = "Usuario")]
    public class UserJobManagersController : Controller
    {
        private CadastroAcademicoContext db = new CadastroAcademicoContext();
        // GET: UserJobManager
        public ActionResult Index()
        {
            var user = db.Users.Where(u => u.UserName.ToLower().Equals(User.Identity.Name)).FirstOrDefault();

            var courses =
                from Registration in db.Registrations
                where Registration.UserId == user.UserId
                select Registration.CourseId;

            var jobs = db.Jobs.Include(j => j.Matter)
                .Include(c => c.Matter.Course)
                .Include(r => r.UserJobs)
                .Where(s => courses.Contains(s.Matter.Course.Id) && (s.Matter.Course.Active==true));
//                .Where(s => courses.Contains(s.Matter.Course.Id) && (s.Matter.Course.Active == true) && ((DateTime.Now >= s.BeginDate) && (DateTime.Now <= s.EndDate)));

            var userJobManagers = new List<UserJobManagerView>();
            foreach (var item in jobs)
            {
                var userJobManagerView = new UserJobManagerView
                {
                    CourseName =item.Matter.Course.Description,
                    JobBeginDate = item.BeginDate,
                    JobDescription = item.Description,
                    JobEndDate = item.EndDate,
                    JobId = item.Id,
                    JobName = item.Name,
                    MatterName = item.Matter.Name,
                    TypeTask = item.TypeTask,
                    //UserJobId = "",
                    //file = =item.UserJobs,
                    //RegistrationDate = "",
                };

                var userJob = db.UserJobs.Where(u => u.UserId == user.UserId && u.JobId == item.Id).FirstOrDefault();

                if (userJob != null)
                {

                    userJobManagerView.UserJobId = userJob.Id;
                    userJobManagerView.filePath = userJob.file;
                    userJobManagerView.RegistrationDate = userJob.RegistrationDate;
                }


                userJobManagers.Add(userJobManagerView);
            }



            return View(userJobManagers);
            
        }

        // GET: Jobs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);

                if (job == null)
            {
                return HttpNotFound();
            }

            var user = db.Users.Where(u => u.UserName.ToLower().Equals(User.Identity.Name)).FirstOrDefault();

            var userJobManagerView = new UserJobManagerView
            {
                CourseName = job.Matter.Course.Description,
                JobBeginDate = job.BeginDate,
                JobDescription = job.Description,
                JobEndDate = job.EndDate,
                JobId = job.Id,
                JobName = job.Name,
                MatterName = job.Matter.Name,
                TypeTask = job.TypeTask,
                //UserJobId = "",
                //file = =item.UserJobs,
                //RegistrationDate = "",
            };

            var userJob = db.UserJobs.Where(u => u.UserId == user.UserId && u.JobId == job.Id).FirstOrDefault();

            if (userJob != null)
            {

                userJobManagerView.UserJobId = userJob.Id;
                userJobManagerView.filePath = userJob.file;
                userJobManagerView.RegistrationDate = userJob.RegistrationDate;
            }

            return View(userJobManagerView);
        }

        // POST: Jobs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UserJobManagerView userJobManagerView)
        {
            if (!ModelState.IsValid)
            {
                return View(userJobManagerView);
            }

            if ((DateTime.Now >= userJobManagerView.JobBeginDate) && (DateTime.Now <= userJobManagerView.JobEndDate))
            {

                //upload image
                string path = string.Empty;
                string pic = string.Empty;
                var user = db.Users.Where(u => u.UserName.ToLower().Equals(User.Identity.Name)).FirstOrDefault();

                if (userJobManagerView.file != null)
                {
                    path = Path.Combine(Server.MapPath("~/App_Data/Jobs"), user.UserId.ToString());
                    if (!Directory.Exists(path))
                        System.IO.Directory.CreateDirectory(path);

                    path = Path.Combine(Server.MapPath("~/App_Data/Jobs"), user.UserId.ToString(), userJobManagerView.JobId.ToString());
                    if (!System.IO.Directory.Exists(path))
                        System.IO.Directory.CreateDirectory(path);

                    path = Server.MapPath(userJobManagerView.filePath);
                    if (System.IO.File.Exists(path))
                        System.IO.File.Delete(path);


                    pic = Path.GetFileName(userJobManagerView.file.FileName);
                    path = Path.Combine(Server.MapPath("~/App_Data/Jobs"), user.UserId.ToString(), userJobManagerView.JobId.ToString(), pic);
                    userJobManagerView.file.SaveAs(path);
                    using (MemoryStream ms = new MemoryStream())
                    {
                        userJobManagerView.file.InputStream.CopyTo(ms);
                        byte[] array = ms.GetBuffer();
                    }
                }

                //Si existe se elimina
                if (userJobManagerView.UserJobId != null)
                {

                    UserJob uJob = db.UserJobs.Find(userJobManagerView.UserJobId);
                    db.UserJobs.Remove(uJob);
                    try
                    {
                        db.SaveChanges();
                    }
                    catch (Exception ex)
                    {
                        if (ex.InnerException != null &&
                            ex.InnerException.InnerException != null &&
                            ex.InnerException.InnerException.Message.Contains("REFERENCE"))
                        {
                            ViewBag.Error = "Can't delete the record, because exist record related";
                        }
                        else
                        {
                            ViewBag.Error = ex.Message;
                        }
                        return View(userJobManagerView);
                    }
                    //Eliminar el fichero fisico
                    //....
                }
                //Se crea nuevo

                var userJob = new UserJob
                {
                    file = pic == string.Empty ? string.Empty : string.Format("~/App_Data/Jobs/{0}/{1}/{2}", user.UserId.ToString(), userJobManagerView.JobId.ToString(), pic),
                    RegistrationDate = DateTime.Now,
                    UserId = user.UserId,
                    JobId = userJobManagerView.JobId

                };

                db.UserJobs.Add(userJob);
                try
                {
                    db.SaveChanges();
                }
                catch (Exception ex)
                {
                    ViewBag.Error = ex.Message;
                    return View(userJobManagerView);
                }
            }
            else
            {
                ViewBag.Error = "No estas en el periodo de entrega";
                return View(userJobManagerView);

            }
            return RedirectToAction("Index");
        }

        private void CreateDirectory(string v)
        {
            throw new NotImplementedException();
        }
    }
}

CadastroAcademico/Views/UserJobManagers/Edit.cshtml
@model CadastroAcademico.Models.UserJobManagerView

@{
    ViewBag.Title = "Edit";
}

<h2>Job</h2>


@using (Html.BeginForm("Edit","UserJobManagers",FormMethod.Post,new { enctype = "multipart/form-data"}))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Upload Job</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.JobId)
        @Html.HiddenFor(model => model.UserJobId)
        @Html.HiddenFor(model => model.filePath)
        @Html.HiddenFor(model => model.JobBeginDate)
        @Html.HiddenFor(model => model.JobEndDate)
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.CourseName)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.CourseName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.MatterName)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.MatterName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model =>model.JobName)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.JobName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.JobDescription)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.JobDescription)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.JobBeginDate)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.JobBeginDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.JobEndDate)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.JobEndDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.TypeTask)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.TypeTask)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.file)
            </dt>
            <dd>
                @if (!string.IsNullOrEmpty(Model.filePath))
                {
                    <a href="@Url.Content(Model.filePath)">
                        @Url.Content(Model.filePath)
                    </a>
                }
            </dd>


            <dt>
                @Html.DisplayNameFor(model => model.file)
            </dt>
            <dd>
                <span class="btn btn-default btn-file">
                    @Html.TextBoxFor(model => model.file, new { type="file" })
                </span>
            </dd>
        </dl>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-warning" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { }, new { @class = "btn btn-success" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CadastroAcademico/Views/UserJobManagers/Index.cshtml
@model IEnumerable<CadastroAcademico.Models.UserJobManagerView>

@{
    ViewBag.Title = "Jobs";
}

<style>
    .modalDialog {
        position: fixed;
        font-family: Arial, Helvetica, sans-serif;
        top: 0;
        right: 0;
        bottom: 0;
        left: 0;
        background: rgba(0,0,0,0.8);
        z-index: 99999;
        opacity: 0;
        -webkit-transition: opacity 400ms ease-in;
        -moz-transition: opacity 400ms ease-in;
        transition: opacity 400ms ease-in;
        pointer-events: none;
    }

        .modalDialog:target {
            opacity: 1;
            pointer-events: auto;
        }

        .modalDialog > div {
            width: 400px;
            position: relative;
            margin: 10% auto;
            padding: 5px 20px 13px 20px;
            border-radius: 10px;
            background: #fff;
            background: -moz-linear-gradient(#fff, #999);
            background: -webkit-linear-gradient(#fff, #999);
            background: -o-linear-gradient(#fff, #999);
        }

    .close {
        background: #606061;
        color: #FFFFFF;
        line-height: 25px;
        position: absolute;
        right: -12px;
        text-align: center;
        top: -10px;
        width: 24px;
        text-decoration: none;
        font-weight: bold;
        -webkit-border-radius: 12px;
        -moz-border-radius: 12px;
        border-radius: 12px;
        -moz-box-shadow: 1px 1px 3px #000;
        -webkit-box-shadow: 1px 1px 3px #000;
        box-shadow: 1px 1px 3px #000;
    }

        .close:hover {
            background: #00d9ff;
        }
</style>
<h2>Jobs</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CourseName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MatterName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.JobName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.JobDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.JobBeginDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.JobEndDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TypeTask)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.file)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RegistrationDate)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr @if (!((@DateTime.Now >= item.JobBeginDate) && (@DateTime.Now <= item.JobEndDate.AddDays(1)))) {  <text>bgcolor="#c3c3c3"</text>} >
        <td>
            @Html.DisplayFor(modelItem => item.CourseName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MatterName)
        </td>
        <td> 
            @Html.DisplayFor(modelItem => item.JobName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.JobDescription)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.JobBeginDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.JobEndDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TypeTask)
        </td>
        <td>
            @if (!string.IsNullOrEmpty(item.filePath))
            {
                <a href="@Url.Content(item.filePath)">
                    @Url.Content(item.filePath)
                </a>

            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RegistrationDate)
        </td>
        <td>
            @if ((@DateTime.Now >= item.JobBeginDate) && (@DateTime.Now <= item.JobEndDate.AddDays(1)))
            {
                
                @Html.ActionLink("subir fichero", "Edit", new { id = item.JobId })
               
                }
                else
                {
                
                    <a href="#openModal">subir fichero</a>

                    <div id="openModal" class="modalDialog">
                        <div>
                            <a href="#close" title="Close" class="close">X</a>
                            <h3>No puedes subir ningun fichero</h3>
                            <p>Las fechas de entrega eran desde @item.JobBeginDate.ToShortDateString() hasta @item.JobEndDate.ToShortDateString()</p>
                        </div>
                    </div>
            
                }

</td>
    </tr>
     }

</table>