CadastroAcademico/Controllers/UserJobsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CadastroAcademico.Models;

namespace CadastroAcademico.Controllers
{
    [Authorize(Roles = "Professor")]
    public class UserJobsController : Controller
    {
        private CadastroAcademicoContext db = new CadastroAcademicoContext();

        // GET: UserJobs
        public ActionResult Index()
        {
            var user = db.Users.Where(u => u.UserName.ToLower().Equals(User.Identity.Name)).FirstOrDefault();
            var userJobs = db.UserJobs
                .Include(u => u.Job)
                .Include(u => u.User)
                .Include(u => u.Job.Matter)
                .Include(u => u.Job.Matter.Course)
                .Where(s => s.Job.Matter.UserId.Equals(user.UserId));

            return View(userJobs.ToList());
        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CadastroAcademico/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Cadastro Academico</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Cadastro Academico", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    @if (this.User.IsInRole("Usuario"))
                    {
                        <li>@Html.ActionLink("Jobs", "Index", "UserJobManagers")</li>
                    }
                    @if (this.User.IsInRole("Professor"))
                    {
                        <li>@Html.ActionLink("Jobs entregados", "Index", "UserJobs")</li>
                        <li>@Html.ActionLink("Courses", "Index", "Courses")</li>
                        <li>@Html.ActionLink("Matters", "Index", "Matters")</li>
                        <li>@Html.ActionLink("Jobs", "Index", "Jobs")</li>
                    }
                    @if (this.User.IsInRole("Administrador"))
                    {
                        <li>@Html.ActionLink("Courses", "Index", "Courses")</li>
                        <li>@Html.ActionLink("Matters", "Index", "Matters")</li>
                        <li>@Html.ActionLink("Jobs", "Index", "Jobs") </li>
                        <li>@Html.ActionLink("Registrations", "Index", "Registrations")</li>
                        <li>@Html.ActionLink("Users", "Index", "Users")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p></p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>